name: operator_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: 2.2.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "../app_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "../app_icon.png"
    icon_size: 48

flutter:
  uses-material-design: true
